ARG PYTHON_VERSION=3.10-slim-buster

FROM python:${PYTHON_VERSION}

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
{% if using_pipenv %}ENV PIPENV_PIPFILE /tmp/Pipfile{% endif %}

RUN mkdir -p /code

WORKDIR /code

{% if using_pipenv %}
COPY Pipfile /tmp/Pipfile

RUN set -ex && \
    pip install --upgrade pip && \
    pip install pipenv && \
    pipenv install && \
    rm -rf /root/.cache/
{% else %}
COPY requirements.txt /tmp/requirements.txt

RUN set -ex && \
    pip install --upgrade pip && \
    pip install -r /tmp/requirements.txt && \
    rm -rf /root/.cache/
{% endif %}

COPY . /code/

{% if using_pipenv %}
RUN ON_FLYIO_SETUP="1" pipenv run python manage.py collectstatic --noinput

EXPOSE 8000

CMD ["pipenv", "run", gunicorn", "--bind", ":8000", "--workers", "2", "{{ django_project_name }}.wsgi"]
{% else %}
RUN ON_FLYIO_SETUP="1" python manage.py collectstatic --noinput

EXPOSE 8000

CMD ["gunicorn", "--bind", ":8000", "--workers", "2", "{{ django_project_name }}.wsgi"]
{% endif %}
